dist: xenial
sudo: true
language: php
php:
  - 5.6
  - 7.1
services:
  - docker
before_install:
  - docker pull ubuntu:16.04
  - docker run -it ubuntu:16.04 bash
before_script:
script:
  - sudo ./install.sh
