dist: xenial
sudo: true
language: php
php:
  - 5.6
  - 7.1
services:
  - docker
before_install:
  - docker pull ubuntu:latest
  - docker run -d ubuntu:latest
before_script:
script:
  - docker exec -t ubuntu:latest sudo ./install.sh
