dist: xenial
sudo: true
language: php
php:
  - 5.6
  - 7.1
services:
  - docker
before_install:
  - docker pull ubuntu:16.04
  - docker run -d ubuntu:16.04
before_script:
script:
  - docker exec -t ubuntu:16.04 sudo ./install.sh
